quarkus.log.category."quest".level = DEBUG

# Configuration JPA
quarkus.datasource.jdbc.url = jdbc:mysql://localhost:3306/projet_quest
quarkus.datasource.username = root
quarkus.datasource.password =

quarkus.hibernate-orm.database.generation = update
quarkus.hibernate-orm.log.sql = true


# - Configuration sécurité -

# Configuration CORS
quarkus.http.cors.enabled = true
quarkus.http.cors.origins = http://localhost:4200

# Configuration accès
quarkus.http.auth.permission.auth.paths = /api/auth
quarkus.http.auth.permission.auth.policy = permit

quarkus.http.auth.permission.inscription.paths = /api/personne/inscription
quarkus.http.auth.permission.inscription.policy = permit

quarkus.http.auth.permission.api.paths = /*
quarkus.http.auth.permission.api.policy = authenticated

# - Configuration JWT -
quarkus.smallrye-jwt.enabled = true

# La clé privée pour signer les jetons
smallrye.jwt.sign.key.location = classpath:privateKey.pem
smallrye.jwt.new-token.lifespan = 3600

# Pour valider le jeton
mp.jwt.verify.issuer = quest-quarkus
mp.jwt.verify.publickey.location = classpath:publicKey.pem
