# Pour exécuter le profile dev : ./mvnw quarkus:dev -Dquarkus.profile=dev

quarkus.http.host = 0.0.0.0

# Configuration JPA
quarkus.datasource.jdbc.url = jdbc:mysql://db:3306/projet_quest
quarkus.datasource.password =
