name: quest

services:
  mysql:
    image: mysql:8.0.45
    container_name: quest-mysql

    networks:
      - quest

    volumes:
      - ./projet_quest.sql:/docker-entrypoint-initdb.d/setup.sql

    environment:
      # - MYSQL_ROOT_PASSWORD=root
      MYSQL_ROOT_PASSWORD: root

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 3s
      retries: 10
      interval: 5s

  java:
    image: ascadis/quest-boot

    # build:
    #   context: ../../../quest_back

    networks:
      - quest

    environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/projet_quest
    SPRING_DATASOURCE_USERNAME: root
    SPRING_DATASOURCE_PASSWORD: root

    # depends_on:
    #   - mysql
    ports:
     - "8080:8080"

    depends_on:
      mysql:
        condition: service_healthy

  phpmyadmin:
    image: phpmyadmin

    networks:
      - quest

    ports:
      - 80:80

    environment:
      # PMA_ARBITRARY: 1
      PMA_HOST: mysql

    depends_on:
      mysql:
        condition: service_healthy
networks:
  quest:
    name: quest
