spring.application.name = formation-spring-boot-security

# Configuration JPA / Hibernate
spring.datasource.url = jdbc:mysql://db:3306/spring_boot
spring.datasource.username = root
spring.datasource.password =

spring.jpa.show-sql = true
# spring.jpa.generate-ddl = true
spring.jpa.hibernate.ddl-auto = update
