spring.application.name=formation-tdd

spring.datasource.url = jdbc:mysql://localhost:3306/formation_tdd
spring.datasource.username = root
spring.datasource.password =

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
