name: quest

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql

    image: ajc/quest-mysql:latest
    container_name: quest-mysql

    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projet_quest

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10

    networks:
      - quest

  java:
    build:
      context: .
      dockerfile: Dockerfile

    image: ajc/quest-boot:latest

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/projet_quest
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - quest

  phpmyadmin:
    image: phpmyadmin

    ports:
      - "80:80"

    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - quest

networks:
  quest:
    name: quest