pipeline {
    agent any

    stages {
         stage('Build Quest Boot') {
            agent {
                docker {
                    image 'maven:3.9-amazoncorretto-21'
                    args '-v $HOME/.m2:/root/.m2:z -u root'
                    reuseNode true
                }
            }
            steps {
                dir('BOOT/quest-boot') {
                     withSonarQubeEnv('SonarQube') {
                        sh "mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Quest-Boot -Dsonar.projectName='Quest Boot'"
                        waitForQualityGate abortPipeline:true
                         
                }
            }
        }
    }

        stage('Docker build') {
            steps {
                dir('BOOT/quest-boot') {
                    sh 'docker build -t ajc/quest-boot .'
                }
            }
        }


    }
}