server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    index index.html;
    root /usr/share/nginx/html;

    location /image {
        proxy_pass http://java:8080/image;

        proxy_set_header Connection "Keep-Alive";
        proxy_set_header Proxy-Connection "Keep-Alive";
    }

    location /phpmyadmin {
        proxy_pass http://phpmyadmin/;

        proxy_set_header Connection "Keep-Alive";
        proxy_set_header Proxy-Connection "Keep-Alive";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}