FROM nginx:latest

WORKDIR /usr/share/nginx/html

# COPY index.html index.html
COPY index.html .
# COPY *.html .
# COPY . .

# COPY index.html /usr/share/nginx/html
# COPY index.html /usr/share/nginx/html/index.html

EXPOSE 80
